### ISSUE TITLE
Supplying passwords on the command line is insecure

### ISSUE THREAD

**Issue by stefanct** [andrewnimmo/rick-sanders-imap-tools#2]
Unfortunately all imap-tools seem to gather the password of users via the `-S` command line switch. This is inherently insecure on shared systems since the command line is visible to all users. Some scripts use a dedicated file of users but with inconsistent command line switches and formats. Also, what's the intention of this repository? Will you maintain the scripts? AFAICT there was no development since the initial import. I have pushed a commit to my fork that changes the default ports to the TLS-enabled default ports btw.

**Comment by andrewnimmo** [comment]
Hi

This repo is made available due to the death of the author and the [subsequent release from license constraints](https://andrewnimmo.github.io/rick-sanders-imap-tools/) for anyone who had purchased a copy. Whilst I continue to use the scripts, no support is currently available. If I have time, I'll pull in relevant changes.
