### ISSUE TITLE
Migrate from SmarterMail local files to imap 

### ISSUE THREAD

**Issue by dfangys** [andrewnimmo/rick-sanders-imap-tools#7]
Hello I have a backup in the local server for SmarterMail extension .grp for users I need to mass migrate to another IMAP server that works with dovecot, also i have the new password with the same email in new server.

any idea ?

**Comment by andrewnimmo** [comment]
Hi. You'll need a different tool because the _IMAP Tools_ work only with a limited number of storage formats (maildir, mbox, mbx) and IMAP connections. For Smartermail, if you only have .grp files and no access to a Smartermail server, you may have to rely on commercial tools, examples of which can be found using a search term like _smartermail migration tool grp files_.
